services:
  functions:
    environment:
      HTTP_PROXY: http://xray:10808
      HTTPS_PROXY: http://xray:10808
      NO_PROXY: localhost,127.0.0.1,api-gw,db,auth,rest,storage,meta,realtime,supavisor
    env_file:
      - .env.functions
