name: Deploy supabase settings

on:
  push:
    branches:
      - "main"
    paths:
      - "supabase/**"
      - "migrations/**"
  pull_request:
    paths:
      - "supabase/**"
      - "migrations/**"

  workflow_dispatch:

concurrency:
  group: production-deploy
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy supabase settings
    runs-on: self-hosted
    steps:
      - name: Set app directory
        run: echo "APP_DIR=$HOME/forma-supabase-backend" >> "$GITHUB_ENV"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Decrypt secrets
        run: |
          set -euo pipefail

          if [[ ! -f .sops.yaml ]]; then
            echo "No .sops.yaml found, skipping decryption"
            exit 0
          fi
          while IFS= read -r encrypted_file; do
            decrypted_file="${encrypted_file%.enc}"

            echo "Decrypting: $encrypted_file"

            sops --decrypt "$encrypted_file" > "$decrypted_file"
            rm "$encrypted_file"
            chmod 444 "$decrypted_file"
          done < <(find . -type f -name '*.enc' -print)

          find "$APP_DIR" -maxdepth 1 -xtype l -delete

      - name: Link supabase settings
        if: github.ref_name != github.event.repository.default_branch
        run: |
          set -euo pipefail
          shopt -s dotglob

          SOURCE_DIR="${{ github.workspace }}/supabase"

          mkdir -p "$APP_DIR"
          for file in "$SOURCE_DIR"/*; do
              [[ -f "$file" ]] || continue
              ln -sfn "$(realpath "$file")" "$APP_DIR/$(basename "$file")"
          done

          rsync -a --delete \
            "$SOURCE_DIR/volumes/functions" \
            "$APP_DIR/volumes"

      - name: Recreate services
        if: github.ref_name != github.event.repository.default_branch
        run: |
          set -euo pipefail

          cd "$APP_DIR"
          sh run.sh recreate functions auth

      - name: Apply supabase migrations
        run: |
          set -euo pipefail
          source supabase/.env
          export POSTGRES_PASSWORD POOLER_TENANT_ID POSTGRES_DB

          SUPABASE_DB_URL="postgresql://postgres.${POOLER_TENANT_ID}:${POSTGRES_PASSWORD}@localhost:5432/${POSTGRES_DB}"

          echo "Checking migrations with dry-run..."
          supabase db push --db-url "$SUPABASE_DB_URL" --dry-run

          if [[ "${{ github.ref_name }}" == "${{ github.event.repository.default_branch }}" ]]; then
            echo "Applying migrations..."
            supabase db push --db-url "$SUPABASE_DB_URL"
          else
            echo "Skip applying migrations..."
          fi
